// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linh.proto

#include "linh.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace linh {
class FileReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FileReq> _instance;
} _FileReq_default_instance_;
class FileResDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FileRes> _instance;
} _FileRes_default_instance_;
}  // namespace linh
static void InitDefaultsFileReq_linh_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::linh::_FileReq_default_instance_;
    new (ptr) ::linh::FileReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::linh::FileReq::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_FileReq_linh_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsFileReq_linh_2eproto}, {}};

static void InitDefaultsFileRes_linh_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::linh::_FileRes_default_instance_;
    new (ptr) ::linh::FileRes();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::linh::FileRes::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_FileRes_linh_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsFileRes_linh_2eproto}, {}};

void InitDefaults_linh_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_FileReq_linh_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_FileRes_linh_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_linh_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_linh_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_linh_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_linh_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::linh::FileReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::linh::FileReq, request_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::linh::FileRes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::linh::FileRes, respond_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::linh::FileReq)},
  { 6, -1, sizeof(::linh::FileRes)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::linh::_FileReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::linh::_FileRes_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_linh_2eproto = {
  {}, AddDescriptors_linh_2eproto, "linh.proto", schemas,
  file_default_instances, TableStruct_linh_2eproto::offsets,
  file_level_metadata_linh_2eproto, 2, file_level_enum_descriptors_linh_2eproto, file_level_service_descriptors_linh_2eproto,
};

const char descriptor_table_protodef_linh_2eproto[] =
  "\n\nlinh.proto\022\004linh\"\032\n\007FileReq\022\017\n\007request"
  "\030\001 \001(\t\"\032\n\007FileRes\022\017\n\007respond\030\001 \001(\t26\n\010Da"
  "taComm\022*\n\010SendFile\022\r.linh.FileReq\032\r.linh"
  ".FileRes\"\000b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_linh_2eproto = {
  false, InitDefaults_linh_2eproto, 
  descriptor_table_protodef_linh_2eproto,
  "linh.proto", &assign_descriptors_table_linh_2eproto, 138,
};

void AddDescriptors_linh_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_linh_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_linh_2eproto = []() { AddDescriptors_linh_2eproto(); return true; }();
namespace linh {

// ===================================================================

void FileReq::InitAsDefaultInstance() {
}
class FileReq::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FileReq::kRequestFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FileReq::FileReq()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:linh.FileReq)
}
FileReq::FileReq(const FileReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  request_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.request().size() > 0) {
    request_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.request_);
  }
  // @@protoc_insertion_point(copy_constructor:linh.FileReq)
}

void FileReq::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_FileReq_linh_2eproto.base);
  request_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

FileReq::~FileReq() {
  // @@protoc_insertion_point(destructor:linh.FileReq)
  SharedDtor();
}

void FileReq::SharedDtor() {
  request_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void FileReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FileReq& FileReq::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_FileReq_linh_2eproto.base);
  return *internal_default_instance();
}


void FileReq::Clear() {
// @@protoc_insertion_point(message_clear_start:linh.FileReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  request_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* FileReq::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<FileReq*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string request = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("linh.FileReq.request");
        object = msg->mutable_request();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool FileReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:linh.FileReq)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string request = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_request()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->request().data(), static_cast<int>(this->request().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "linh.FileReq.request"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:linh.FileReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:linh.FileReq)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void FileReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:linh.FileReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string request = 1;
  if (this->request().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->request().data(), static_cast<int>(this->request().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "linh.FileReq.request");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->request(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:linh.FileReq)
}

::google::protobuf::uint8* FileReq::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:linh.FileReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string request = 1;
  if (this->request().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->request().data(), static_cast<int>(this->request().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "linh.FileReq.request");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->request(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:linh.FileReq)
  return target;
}

size_t FileReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:linh.FileReq)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string request = 1;
  if (this->request().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->request());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FileReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:linh.FileReq)
  GOOGLE_DCHECK_NE(&from, this);
  const FileReq* source =
      ::google::protobuf::DynamicCastToGenerated<FileReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:linh.FileReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:linh.FileReq)
    MergeFrom(*source);
  }
}

void FileReq::MergeFrom(const FileReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:linh.FileReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.request().size() > 0) {

    request_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.request_);
  }
}

void FileReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:linh.FileReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FileReq::CopyFrom(const FileReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:linh.FileReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FileReq::IsInitialized() const {
  return true;
}

void FileReq::Swap(FileReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FileReq::InternalSwap(FileReq* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  request_.Swap(&other->request_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata FileReq::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_linh_2eproto);
  return ::file_level_metadata_linh_2eproto[kIndexInFileMessages];
}


// ===================================================================

void FileRes::InitAsDefaultInstance() {
}
class FileRes::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FileRes::kRespondFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FileRes::FileRes()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:linh.FileRes)
}
FileRes::FileRes(const FileRes& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  respond_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.respond().size() > 0) {
    respond_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.respond_);
  }
  // @@protoc_insertion_point(copy_constructor:linh.FileRes)
}

void FileRes::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_FileRes_linh_2eproto.base);
  respond_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

FileRes::~FileRes() {
  // @@protoc_insertion_point(destructor:linh.FileRes)
  SharedDtor();
}

void FileRes::SharedDtor() {
  respond_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void FileRes::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FileRes& FileRes::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_FileRes_linh_2eproto.base);
  return *internal_default_instance();
}


void FileRes::Clear() {
// @@protoc_insertion_point(message_clear_start:linh.FileRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  respond_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* FileRes::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<FileRes*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string respond = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("linh.FileRes.respond");
        object = msg->mutable_respond();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool FileRes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:linh.FileRes)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string respond = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_respond()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->respond().data(), static_cast<int>(this->respond().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "linh.FileRes.respond"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:linh.FileRes)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:linh.FileRes)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void FileRes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:linh.FileRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string respond = 1;
  if (this->respond().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->respond().data(), static_cast<int>(this->respond().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "linh.FileRes.respond");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->respond(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:linh.FileRes)
}

::google::protobuf::uint8* FileRes::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:linh.FileRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string respond = 1;
  if (this->respond().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->respond().data(), static_cast<int>(this->respond().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "linh.FileRes.respond");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->respond(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:linh.FileRes)
  return target;
}

size_t FileRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:linh.FileRes)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string respond = 1;
  if (this->respond().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->respond());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FileRes::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:linh.FileRes)
  GOOGLE_DCHECK_NE(&from, this);
  const FileRes* source =
      ::google::protobuf::DynamicCastToGenerated<FileRes>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:linh.FileRes)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:linh.FileRes)
    MergeFrom(*source);
  }
}

void FileRes::MergeFrom(const FileRes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:linh.FileRes)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.respond().size() > 0) {

    respond_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.respond_);
  }
}

void FileRes::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:linh.FileRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FileRes::CopyFrom(const FileRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:linh.FileRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FileRes::IsInitialized() const {
  return true;
}

void FileRes::Swap(FileRes* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FileRes::InternalSwap(FileRes* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  respond_.Swap(&other->respond_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata FileRes::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_linh_2eproto);
  return ::file_level_metadata_linh_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace linh
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::linh::FileReq* Arena::CreateMaybeMessage< ::linh::FileReq >(Arena* arena) {
  return Arena::CreateInternal< ::linh::FileReq >(arena);
}
template<> PROTOBUF_NOINLINE ::linh::FileRes* Arena::CreateMaybeMessage< ::linh::FileRes >(Arena* arena) {
  return Arena::CreateInternal< ::linh::FileRes >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
