// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linh.proto

#ifndef PROTOBUF_INCLUDED_linh_2eproto
#define PROTOBUF_INCLUDED_linh_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_linh_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_linh_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_linh_2eproto();
namespace linh {
class FileReq;
class FileReqDefaultTypeInternal;
extern FileReqDefaultTypeInternal _FileReq_default_instance_;
class FileRes;
class FileResDefaultTypeInternal;
extern FileResDefaultTypeInternal _FileRes_default_instance_;
}  // namespace linh
namespace google {
namespace protobuf {
template<> ::linh::FileReq* Arena::CreateMaybeMessage<::linh::FileReq>(Arena*);
template<> ::linh::FileRes* Arena::CreateMaybeMessage<::linh::FileRes>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace linh {

// ===================================================================

class FileReq final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:linh.FileReq) */ {
 public:
  FileReq();
  virtual ~FileReq();

  FileReq(const FileReq& from);

  inline FileReq& operator=(const FileReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FileReq(FileReq&& from) noexcept
    : FileReq() {
    *this = ::std::move(from);
  }

  inline FileReq& operator=(FileReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const FileReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FileReq* internal_default_instance() {
    return reinterpret_cast<const FileReq*>(
               &_FileReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(FileReq* other);
  friend void swap(FileReq& a, FileReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FileReq* New() const final {
    return CreateMaybeMessage<FileReq>(nullptr);
  }

  FileReq* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FileReq>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FileReq& from);
  void MergeFrom(const FileReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string request = 1;
  void clear_request();
  static const int kRequestFieldNumber = 1;
  const ::std::string& request() const;
  void set_request(const ::std::string& value);
  #if LANG_CXX11
  void set_request(::std::string&& value);
  #endif
  void set_request(const char* value);
  void set_request(const char* value, size_t size);
  ::std::string* mutable_request();
  ::std::string* release_request();
  void set_allocated_request(::std::string* request);

  // @@protoc_insertion_point(class_scope:linh.FileReq)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr request_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_linh_2eproto;
};
// -------------------------------------------------------------------

class FileRes final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:linh.FileRes) */ {
 public:
  FileRes();
  virtual ~FileRes();

  FileRes(const FileRes& from);

  inline FileRes& operator=(const FileRes& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FileRes(FileRes&& from) noexcept
    : FileRes() {
    *this = ::std::move(from);
  }

  inline FileRes& operator=(FileRes&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const FileRes& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FileRes* internal_default_instance() {
    return reinterpret_cast<const FileRes*>(
               &_FileRes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(FileRes* other);
  friend void swap(FileRes& a, FileRes& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FileRes* New() const final {
    return CreateMaybeMessage<FileRes>(nullptr);
  }

  FileRes* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FileRes>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FileRes& from);
  void MergeFrom(const FileRes& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string respond = 1;
  void clear_respond();
  static const int kRespondFieldNumber = 1;
  const ::std::string& respond() const;
  void set_respond(const ::std::string& value);
  #if LANG_CXX11
  void set_respond(::std::string&& value);
  #endif
  void set_respond(const char* value);
  void set_respond(const char* value, size_t size);
  ::std::string* mutable_respond();
  ::std::string* release_respond();
  void set_allocated_respond(::std::string* respond);

  // @@protoc_insertion_point(class_scope:linh.FileRes)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr respond_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_linh_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FileReq

// string request = 1;
inline void FileReq::clear_request() {
  request_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FileReq::request() const {
  // @@protoc_insertion_point(field_get:linh.FileReq.request)
  return request_.GetNoArena();
}
inline void FileReq::set_request(const ::std::string& value) {
  
  request_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:linh.FileReq.request)
}
#if LANG_CXX11
inline void FileReq::set_request(::std::string&& value) {
  
  request_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:linh.FileReq.request)
}
#endif
inline void FileReq::set_request(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  request_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:linh.FileReq.request)
}
inline void FileReq::set_request(const char* value, size_t size) {
  
  request_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:linh.FileReq.request)
}
inline ::std::string* FileReq::mutable_request() {
  
  // @@protoc_insertion_point(field_mutable:linh.FileReq.request)
  return request_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FileReq::release_request() {
  // @@protoc_insertion_point(field_release:linh.FileReq.request)
  
  return request_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileReq::set_allocated_request(::std::string* request) {
  if (request != nullptr) {
    
  } else {
    
  }
  request_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), request);
  // @@protoc_insertion_point(field_set_allocated:linh.FileReq.request)
}

// -------------------------------------------------------------------

// FileRes

// string respond = 1;
inline void FileRes::clear_respond() {
  respond_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FileRes::respond() const {
  // @@protoc_insertion_point(field_get:linh.FileRes.respond)
  return respond_.GetNoArena();
}
inline void FileRes::set_respond(const ::std::string& value) {
  
  respond_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:linh.FileRes.respond)
}
#if LANG_CXX11
inline void FileRes::set_respond(::std::string&& value) {
  
  respond_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:linh.FileRes.respond)
}
#endif
inline void FileRes::set_respond(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  respond_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:linh.FileRes.respond)
}
inline void FileRes::set_respond(const char* value, size_t size) {
  
  respond_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:linh.FileRes.respond)
}
inline ::std::string* FileRes::mutable_respond() {
  
  // @@protoc_insertion_point(field_mutable:linh.FileRes.respond)
  return respond_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FileRes::release_respond() {
  // @@protoc_insertion_point(field_release:linh.FileRes.respond)
  
  return respond_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileRes::set_allocated_respond(::std::string* respond) {
  if (respond != nullptr) {
    
  } else {
    
  }
  respond_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), respond);
  // @@protoc_insertion_point(field_set_allocated:linh.FileRes.respond)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace linh

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_linh_2eproto
