// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: linh.proto
#ifndef GRPC_linh_2eproto__INCLUDED
#define GRPC_linh_2eproto__INCLUDED

#include "linh.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class Channel;
class CompletionQueue;
class ServerCompletionQueue;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc_impl

namespace grpc {
class ServerContext;
}  // namespace grpc

namespace linh {

class DataComm final {
 public:
  static constexpr char const* service_full_name() {
    return "linh.DataComm";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendFile(::grpc::ClientContext* context, const ::linh::FileReq& request, ::linh::FileRes* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::linh::FileRes>> AsyncSendFile(::grpc::ClientContext* context, const ::linh::FileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::linh::FileRes>>(AsyncSendFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::linh::FileRes>> PrepareAsyncSendFile(::grpc::ClientContext* context, const ::linh::FileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::linh::FileRes>>(PrepareAsyncSendFileRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void SendFile(::grpc::ClientContext* context, const ::linh::FileReq* request, ::linh::FileRes* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendFile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::linh::FileRes* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendFile(::grpc::ClientContext* context, const ::linh::FileReq* request, ::linh::FileRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void SendFile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::linh::FileRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::linh::FileRes>* AsyncSendFileRaw(::grpc::ClientContext* context, const ::linh::FileReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::linh::FileRes>* PrepareAsyncSendFileRaw(::grpc::ClientContext* context, const ::linh::FileReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SendFile(::grpc::ClientContext* context, const ::linh::FileReq& request, ::linh::FileRes* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::linh::FileRes>> AsyncSendFile(::grpc::ClientContext* context, const ::linh::FileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::linh::FileRes>>(AsyncSendFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::linh::FileRes>> PrepareAsyncSendFile(::grpc::ClientContext* context, const ::linh::FileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::linh::FileRes>>(PrepareAsyncSendFileRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SendFile(::grpc::ClientContext* context, const ::linh::FileReq* request, ::linh::FileRes* response, std::function<void(::grpc::Status)>) override;
      void SendFile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::linh::FileRes* response, std::function<void(::grpc::Status)>) override;
      void SendFile(::grpc::ClientContext* context, const ::linh::FileReq* request, ::linh::FileRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void SendFile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::linh::FileRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::linh::FileRes>* AsyncSendFileRaw(::grpc::ClientContext* context, const ::linh::FileReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::linh::FileRes>* PrepareAsyncSendFileRaw(::grpc::ClientContext* context, const ::linh::FileReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendFile_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendFile(::grpc::ServerContext* context, const ::linh::FileReq* request, ::linh::FileRes* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SendFile() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFile(::grpc::ServerContext* context, const ::linh::FileReq* request, ::linh::FileRes* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendFile(::grpc::ServerContext* context, ::linh::FileReq* request, ::grpc::ServerAsyncResponseWriter< ::linh::FileRes>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendFile<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SendFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_SendFile() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::linh::FileReq, ::linh::FileRes>(
          [this](::grpc::ServerContext* context,
                 const ::linh::FileReq* request,
                 ::linh::FileRes* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->SendFile(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_SendFile(
        ::grpc::experimental::MessageAllocator< ::linh::FileReq, ::linh::FileRes>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::linh::FileReq, ::linh::FileRes>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SendFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFile(::grpc::ServerContext* context, const ::linh::FileReq* request, ::linh::FileRes* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void SendFile(::grpc::ServerContext* context, const ::linh::FileReq* request, ::linh::FileRes* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_SendFile<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SendFile() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFile(::grpc::ServerContext* context, const ::linh::FileReq* request, ::linh::FileRes* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_SendFile() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFile(::grpc::ServerContext* context, const ::linh::FileReq* request, ::linh::FileRes* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendFile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SendFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_SendFile() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->SendFile(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_SendFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFile(::grpc::ServerContext* context, const ::linh::FileReq* request, ::linh::FileRes* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void SendFile(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_SendFile() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::linh::FileReq, ::linh::FileRes>(std::bind(&WithStreamedUnaryMethod_SendFile<BaseClass>::StreamedSendFile, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_SendFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendFile(::grpc::ServerContext* context, const ::linh::FileReq* request, ::linh::FileRes* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendFile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::linh::FileReq,::linh::FileRes>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendFile<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendFile<Service > StreamedService;
};

}  // namespace linh


#endif  // GRPC_linh_2eproto__INCLUDED
